SystemOrganization addCategory: #'Iceberg-Libgit'!
SystemOrganization addCategory: #'Iceberg-Libgit-Changes'!
SystemOrganization addCategory: #'Iceberg-Libgit-Commit'!
SystemOrganization addCategory: #'Iceberg-Libgit-Core'!
SystemOrganization addCategory: #'Iceberg-Libgit-Exceptions'!
SystemOrganization addCategory: #'Iceberg-Libgit-GitActions'!
SystemOrganization addCategory: #'Iceberg-Libgit-Writing'!
