accessing
help
	^ 'You can checkout a new or existing branch and merge your image into it.
This will not lose any change in the image but open a merge view is necessary.

This situation happens because the code loaded in your image does not correspond with the status of your repository.

This operation will modify the state of your working copy in disk. All non-commited changes in your disk working copy that are not in the image will be lost. If you want to keep them, perform a commit from outside before.'