SystemOrganization addCategory: #'Iceberg-Plugin-GitHub'!
SystemOrganization addCategory: #'Iceberg-Plugin-GitHub-Commands'!
SystemOrganization addCategory: #'Iceberg-Plugin-GitHub-Core'!
SystemOrganization addCategory: #'Iceberg-Plugin-GitHub-Manifest'!
SystemOrganization addCategory: #'Iceberg-Plugin-GitHub-Model'!
SystemOrganization addCategory: #'Iceberg-Plugin-GitHub-Utils'!
SystemOrganization addCategory: #'Iceberg-Plugin-GitHub-View'!
