SystemOrganization addCategory: #'Iceberg-Plugin-GitHub'!
SystemOrganization addCategory: #'Iceberg-Plugin-GitHub-Authentication'!
SystemOrganization addCategory: #'Iceberg-Plugin-GitHub-Commands'!
SystemOrganization addCategory: #'Iceberg-Plugin-GitHub-Model'!
SystemOrganization addCategory: #'Iceberg-Plugin-GitHub-Old'!
SystemOrganization addCategory: #'Iceberg-Plugin-GitHub-Utils'!
SystemOrganization addCategory: #'Iceberg-Plugin-GitHub-View'!
