accessing
help
	^ 'Discard all changes in your image and checkout an existing branch.
This action will checkout the branch in the repository and align your image with your repository.

This situation happens because the code loaded in your image does not correspond with the status of your repository.

Opens a preview window before doing any change.

This operation will modify the state of your working copy in disk. All non-commited changes in your disk working copy that are not in the image will be lost. If you want to keep them, perform a commit from outside before.'