SystemOrganization addCategory: #'Iceberg-TipUI'!
SystemOrganization addCategory: #'Iceberg-TipUI-Commands'!
SystemOrganization addCategory: #'Iceberg-TipUI-Model'!
SystemOrganization addCategory: #'Iceberg-TipUI-View'!
SystemOrganization addCategory: #'Iceberg-TipUI-View-DataSource'!
SystemOrganization addCategory: #'Iceberg-TipUI-View-ReadOnlyForm'!
SystemOrganization addCategory: #'Iceberg-TipUI-View-Toolbar'!
