name: Iceberg-Pharo-Integration

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest ]
        smalltalk: [ Pharo64-alpha ]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.smalltalk }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup smalltalkCI
        uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - name: Load Image and Run Release Tests
        run: smalltalkci -s ${{ matrix.smalltalk }} .smalltalk.release.ston
        timeout-minutes: 10
      - name: Clean Up
        run: rm -Rf ${{ env.SMALLTALK_CI_BUILD }}
      - name: Load Image and Run Tests
        run: smalltalkci -s ${{ matrix.smalltalk }} .smalltalk.all.ston
        timeout-minutes: 20